name: CI

on:
  pull_request:
  push:
    branches:
      - master
      - "releases/**"

jobs:
  lint-test-build:
    name: Lint, tests, and build
    permissions:
      contents: read
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: js-src
    steps:
      - uses: actions/checkout@v5
      - uses: pnpm/action-setup@v4
      - name: Install Node.js
        uses: actions/setup-node@v6
        with:
          node-version: "22.11.0"
          cache: "pnpm"
          cache-dependency-path: js-src/pnpm-lock.yaml
      - name: Install dependencies
        run: pnpm install
      - name: Audit
        run: pnpm run audit

      - name: CORE-UI - Type check
        run: |
          cd packages/core-ui
          pnpm run type-check
      - name: CORE-UI - Lint and format check
        run: |
          cd packages/core-ui
          pnpm run ci:lint-format
      - name: CORE-UI - Run coverage
        run: |
          cd packages/core-ui
          pnpm run coverage
      - name: CORE-UI - Build
        run: |
          cd packages/core-ui
          pnpm run build

      - name: SCRIPTING-EDITOR - Type check
        run: |
          cd packages/scripting-editor
          pnpm run type-check
      - name: SCRIPTING-EDITOR - Lint and format check
        run: |
          cd packages/scripting-editor
          pnpm run ci:lint-format
      - name: SCRIPTING-EDITOR - Run coverage
        run: |
          cd packages/scripting-editor
          pnpm run coverage
      - name: SCRIPTING-EDITOR - Build
        run: |
          cd packages/scripting-editor
          pnpm run build

      - name: Upload scripting-editor build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: scripting-editor-dist
          path: js-src/packages/scripting-editor/dist/**
